# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('snipet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Snippet')),
            ],
        ),
    ]
