# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippetdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetdetail',
            name='snipet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='snippets.Snippet'),
        ),
    ]
