# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20180411_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetdetail',
            old_name='snipet',
            new_name='snippet',
        ),
    ]
