# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20180412_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetdetail',
            name='snippet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='snippets.Snippet'),
        ),
    ]
