# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20180412_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetdetail',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
